name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python and create virtual environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python and activate virtual environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Playwright browsers
      run: |
        pip install pytest-playwright
        playwright install

    - name: Run tests
      run: |
        pytest
